# Generated by Django 3.0.6 on 2020-05-24 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=30)),
                ('goal_id', models.IntegerField(default=1)),
                ('created_by', models.CharField(max_length=30)),
                ('moved_by', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goals.GoalStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ScrumyGoals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
